#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# version requirements, https://github.com/opscode-cookbooks/apt#requirements
# older version is used explicitly for Chef 10 support
cookbook 'apt',
  :git => 'https://github.com/opscode-cookbooks/apt',
  :ref => '1.7.0'
    
cookbook 'cron',
  :git => 'https://github.com/opscode-cookbooks/cron',
  :ref => 'v1.2.8'

cookbook 'ntp',
  :git => 'https://github.com/opscode-cookbooks/ntp',
  :ref => 'v1.4.0'

cookbook 'postfix',
  :git => 'https://github.com/opscode-cookbooks/postfix',
  :ref => 'v3.0.0'

cookbook 'sudo',
  :git => 'https://github.com/opscode-cookbooks/sudo',
  :ref => 'v2.2.0'

cookbook 'system',
  :git => 'https://github.com/xhost-cookbooks/system',
  :ref => 'v0.0.1'

# TODO: contribute enhancements back upstream to Opscode
cookbook 'resolver',
  :git => 'https://github.com/flaccid/cookbooks',
  :path => 'cookbooks/resolver',
  :ref => 'master'
